/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DbcParsedData } from "./DbcParsedData";
import { DbcParsedDataCountArgs } from "./DbcParsedDataCountArgs";
import { DbcParsedDataFindManyArgs } from "./DbcParsedDataFindManyArgs";
import { DbcParsedDataFindUniqueArgs } from "./DbcParsedDataFindUniqueArgs";
import { CreateDbcParsedDataArgs } from "./CreateDbcParsedDataArgs";
import { UpdateDbcParsedDataArgs } from "./UpdateDbcParsedDataArgs";
import { DeleteDbcParsedDataArgs } from "./DeleteDbcParsedDataArgs";
import { DbcCategory } from "../../dbcCategory/base/DbcCategory";
import { Device } from "../../device/base/Device";
import { FileImportLog } from "../../fileImportLog/base/FileImportLog";
import { User } from "../../user/base/User";
import { DbcParsedDataService } from "../dbcParsedData.service";
@graphql.Resolver(() => DbcParsedData)
export class DbcParsedDataResolverBase {
  constructor(protected readonly service: DbcParsedDataService) {}

  async _dbcParsedDataItemsMeta(
    @graphql.Args() args: DbcParsedDataCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [DbcParsedData])
  async dbcParsedDataItems(
    @graphql.Args() args: DbcParsedDataFindManyArgs
  ): Promise<DbcParsedData[]> {
    return this.service.dbcParsedDataItems(args);
  }

  @graphql.Query(() => DbcParsedData, { nullable: true })
  async dbcParsedData(
    @graphql.Args() args: DbcParsedDataFindUniqueArgs
  ): Promise<DbcParsedData | null> {
    const result = await this.service.dbcParsedData(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DbcParsedData)
  async createDbcParsedData(
    @graphql.Args() args: CreateDbcParsedDataArgs
  ): Promise<DbcParsedData> {
    return await this.service.createDbcParsedData({
      ...args,
      data: {
        ...args.data,

        dbcCategory: args.data.dbcCategory
          ? {
              connect: args.data.dbcCategory,
            }
          : undefined,

        device: args.data.device
          ? {
              connect: args.data.device,
            }
          : undefined,

        fileImportLog: args.data.fileImportLog
          ? {
              connect: args.data.fileImportLog,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => DbcParsedData)
  async updateDbcParsedData(
    @graphql.Args() args: UpdateDbcParsedDataArgs
  ): Promise<DbcParsedData | null> {
    try {
      return await this.service.updateDbcParsedData({
        ...args,
        data: {
          ...args.data,

          dbcCategory: args.data.dbcCategory
            ? {
                connect: args.data.dbcCategory,
              }
            : undefined,

          device: args.data.device
            ? {
                connect: args.data.device,
              }
            : undefined,

          fileImportLog: args.data.fileImportLog
            ? {
                connect: args.data.fileImportLog,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DbcParsedData)
  async deleteDbcParsedData(
    @graphql.Args() args: DeleteDbcParsedDataArgs
  ): Promise<DbcParsedData | null> {
    try {
      return await this.service.deleteDbcParsedData(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => DbcCategory, {
    nullable: true,
    name: "dbcCategory",
  })
  async getDbcCategory(
    @graphql.Parent() parent: DbcParsedData
  ): Promise<DbcCategory | null> {
    const result = await this.service.getDbcCategory(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Device, {
    nullable: true,
    name: "device",
  })
  async getDevice(
    @graphql.Parent() parent: DbcParsedData
  ): Promise<Device | null> {
    const result = await this.service.getDevice(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => FileImportLog, {
    nullable: true,
    name: "fileImportLog",
  })
  async getFileImportLog(
    @graphql.Parent() parent: DbcParsedData
  ): Promise<FileImportLog | null> {
    const result = await this.service.getFileImportLog(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: DbcParsedData): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
