/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DbcParsedDataService } from "../dbcParsedData.service";
import { DbcParsedDataCreateInput } from "./DbcParsedDataCreateInput";
import { DbcParsedData } from "./DbcParsedData";
import { DbcParsedDataFindManyArgs } from "./DbcParsedDataFindManyArgs";
import { DbcParsedDataWhereUniqueInput } from "./DbcParsedDataWhereUniqueInput";
import { DbcParsedDataUpdateInput } from "./DbcParsedDataUpdateInput";

export class DbcParsedDataControllerBase {
  constructor(protected readonly service: DbcParsedDataService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DbcParsedData })
  async createDbcParsedData(
    @common.Body() data: DbcParsedDataCreateInput
  ): Promise<DbcParsedData> {
    return await this.service.createDbcParsedData({
      data: {
        ...data,

        dbcCategory: data.dbcCategory
          ? {
              connect: data.dbcCategory,
            }
          : undefined,

        device: data.device
          ? {
              connect: data.device,
            }
          : undefined,

        fileImportLog: data.fileImportLog
          ? {
              connect: data.fileImportLog,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        codeName: true,
        codeValue: true,
        createdAt: true,
        dataType: true,

        dbcCategory: {
          select: {
            id: true,
          },
        },

        description: true,

        device: {
          select: {
            id: true,
          },
        },

        fileImportLog: {
          select: {
            id: true,
          },
        },

        id: true,
        rawData: true,
        sourceLine: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        valid: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [DbcParsedData] })
  @ApiNestedQuery(DbcParsedDataFindManyArgs)
  async dbcParsedDataItems(
    @common.Req() request: Request
  ): Promise<DbcParsedData[]> {
    const args = plainToClass(DbcParsedDataFindManyArgs, request.query);
    return this.service.dbcParsedDataItems({
      ...args,
      select: {
        codeName: true,
        codeValue: true,
        createdAt: true,
        dataType: true,

        dbcCategory: {
          select: {
            id: true,
          },
        },

        description: true,

        device: {
          select: {
            id: true,
          },
        },

        fileImportLog: {
          select: {
            id: true,
          },
        },

        id: true,
        rawData: true,
        sourceLine: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        valid: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DbcParsedData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async dbcParsedData(
    @common.Param() params: DbcParsedDataWhereUniqueInput
  ): Promise<DbcParsedData | null> {
    const result = await this.service.dbcParsedData({
      where: params,
      select: {
        codeName: true,
        codeValue: true,
        createdAt: true,
        dataType: true,

        dbcCategory: {
          select: {
            id: true,
          },
        },

        description: true,

        device: {
          select: {
            id: true,
          },
        },

        fileImportLog: {
          select: {
            id: true,
          },
        },

        id: true,
        rawData: true,
        sourceLine: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        valid: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DbcParsedData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDbcParsedData(
    @common.Param() params: DbcParsedDataWhereUniqueInput,
    @common.Body() data: DbcParsedDataUpdateInput
  ): Promise<DbcParsedData | null> {
    try {
      return await this.service.updateDbcParsedData({
        where: params,
        data: {
          ...data,

          dbcCategory: data.dbcCategory
            ? {
                connect: data.dbcCategory,
              }
            : undefined,

          device: data.device
            ? {
                connect: data.device,
              }
            : undefined,

          fileImportLog: data.fileImportLog
            ? {
                connect: data.fileImportLog,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          codeName: true,
          codeValue: true,
          createdAt: true,
          dataType: true,

          dbcCategory: {
            select: {
              id: true,
            },
          },

          description: true,

          device: {
            select: {
              id: true,
            },
          },

          fileImportLog: {
            select: {
              id: true,
            },
          },

          id: true,
          rawData: true,
          sourceLine: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          valid: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DbcParsedData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDbcParsedData(
    @common.Param() params: DbcParsedDataWhereUniqueInput
  ): Promise<DbcParsedData | null> {
    try {
      return await this.service.deleteDbcParsedData({
        where: params,
        select: {
          codeName: true,
          codeValue: true,
          createdAt: true,
          dataType: true,

          dbcCategory: {
            select: {
              id: true,
            },
          },

          description: true,

          device: {
            select: {
              id: true,
            },
          },

          fileImportLog: {
            select: {
              id: true,
            },
          },

          id: true,
          rawData: true,
          sourceLine: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          valid: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
