/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DbcParsedDataService } from "../dbcParsedData.service";
import { DbcParsedDataCreateInput } from "./DbcParsedDataCreateInput";
import { DbcParsedData } from "./DbcParsedData";
import { DbcParsedDataFindManyArgs } from "./DbcParsedDataFindManyArgs";
import { DbcParsedDataWhereUniqueInput } from "./DbcParsedDataWhereUniqueInput";
import { DbcParsedDataUpdateInput } from "./DbcParsedDataUpdateInput";

export class DbcParsedDataControllerBase {
  constructor(protected readonly service: DbcParsedDataService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DbcParsedData })
  async createDbcParsedData(
    @common.Body() data: DbcParsedDataCreateInput
  ): Promise<DbcParsedData> {
    return await this.service.createDbcParsedData({
      data: {
        ...data,

        dbcCategory: data.dbcCategory
          ? {
              connect: data.dbcCategory,
            }
          : undefined,
      },
      select: {
        codeName: true,
        codeValue: true,
        createdAt: true,

        dbcCategory: {
          select: {
            id: true,
          },
        },

        description: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [DbcParsedData] })
  @ApiNestedQuery(DbcParsedDataFindManyArgs)
  async dbcParsedDataItems(
    @common.Req() request: Request
  ): Promise<DbcParsedData[]> {
    const args = plainToClass(DbcParsedDataFindManyArgs, request.query);
    return this.service.dbcParsedDataItems({
      ...args,
      select: {
        codeName: true,
        codeValue: true,
        createdAt: true,

        dbcCategory: {
          select: {
            id: true,
          },
        },

        description: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DbcParsedData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async dbcParsedData(
    @common.Param() params: DbcParsedDataWhereUniqueInput
  ): Promise<DbcParsedData | null> {
    const result = await this.service.dbcParsedData({
      where: params,
      select: {
        codeName: true,
        codeValue: true,
        createdAt: true,

        dbcCategory: {
          select: {
            id: true,
          },
        },

        description: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DbcParsedData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDbcParsedData(
    @common.Param() params: DbcParsedDataWhereUniqueInput,
    @common.Body() data: DbcParsedDataUpdateInput
  ): Promise<DbcParsedData | null> {
    try {
      return await this.service.updateDbcParsedData({
        where: params,
        data: {
          ...data,

          dbcCategory: data.dbcCategory
            ? {
                connect: data.dbcCategory,
              }
            : undefined,
        },
        select: {
          codeName: true,
          codeValue: true,
          createdAt: true,

          dbcCategory: {
            select: {
              id: true,
            },
          },

          description: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DbcParsedData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDbcParsedData(
    @common.Param() params: DbcParsedDataWhereUniqueInput
  ): Promise<DbcParsedData | null> {
    try {
      return await this.service.deleteDbcParsedData({
        where: params,
        select: {
          codeName: true,
          codeValue: true,
          createdAt: true,

          dbcCategory: {
            select: {
              id: true,
            },
          },

          description: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
