/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  DbcParsedData as PrismaDbcParsedData,
  DbcCategory as PrismaDbcCategory,
  Device as PrismaDevice,
  FileImportLog as PrismaFileImportLog,
  User as PrismaUser,
} from "@prisma/client";

export class DbcParsedDataServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DbcParsedDataCountArgs, "select">
  ): Promise<number> {
    return this.prisma.dbcParsedData.count(args);
  }

  async dbcParsedDataItems(
    args: Prisma.DbcParsedDataFindManyArgs
  ): Promise<PrismaDbcParsedData[]> {
    return this.prisma.dbcParsedData.findMany(args);
  }
  async dbcParsedData(
    args: Prisma.DbcParsedDataFindUniqueArgs
  ): Promise<PrismaDbcParsedData | null> {
    return this.prisma.dbcParsedData.findUnique(args);
  }
  async createDbcParsedData(
    args: Prisma.DbcParsedDataCreateArgs
  ): Promise<PrismaDbcParsedData> {
    return this.prisma.dbcParsedData.create(args);
  }
  async updateDbcParsedData(
    args: Prisma.DbcParsedDataUpdateArgs
  ): Promise<PrismaDbcParsedData> {
    return this.prisma.dbcParsedData.update(args);
  }
  async deleteDbcParsedData(
    args: Prisma.DbcParsedDataDeleteArgs
  ): Promise<PrismaDbcParsedData> {
    return this.prisma.dbcParsedData.delete(args);
  }

  async getDbcCategory(parentId: string): Promise<PrismaDbcCategory | null> {
    return this.prisma.dbcParsedData
      .findUnique({
        where: { id: parentId },
      })
      .dbcCategory();
  }

  async getDevice(parentId: string): Promise<PrismaDevice | null> {
    return this.prisma.dbcParsedData
      .findUnique({
        where: { id: parentId },
      })
      .device();
  }

  async getFileImportLog(
    parentId: string
  ): Promise<PrismaFileImportLog | null> {
    return this.prisma.dbcParsedData
      .findUnique({
        where: { id: parentId },
      })
      .fileImportLog();
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.dbcParsedData
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
