/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  DbcCategory as PrismaDbcCategory,
  DbcParsedData as PrismaDbcParsedData,
} from "@prisma/client";

export class DbcCategoryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DbcCategoryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.dbcCategory.count(args);
  }

  async dbcCategories(
    args: Prisma.DbcCategoryFindManyArgs
  ): Promise<PrismaDbcCategory[]> {
    return this.prisma.dbcCategory.findMany(args);
  }
  async dbcCategory(
    args: Prisma.DbcCategoryFindUniqueArgs
  ): Promise<PrismaDbcCategory | null> {
    return this.prisma.dbcCategory.findUnique(args);
  }
  async createDbcCategory(
    args: Prisma.DbcCategoryCreateArgs
  ): Promise<PrismaDbcCategory> {
    return this.prisma.dbcCategory.create(args);
  }
  async updateDbcCategory(
    args: Prisma.DbcCategoryUpdateArgs
  ): Promise<PrismaDbcCategory> {
    return this.prisma.dbcCategory.update(args);
  }
  async deleteDbcCategory(
    args: Prisma.DbcCategoryDeleteArgs
  ): Promise<PrismaDbcCategory> {
    return this.prisma.dbcCategory.delete(args);
  }

  async findDbcParsedDataItems(
    parentId: string,
    args: Prisma.DbcParsedDataFindManyArgs
  ): Promise<PrismaDbcParsedData[]> {
    return this.prisma.dbcCategory
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .dbcParsedDataItems(args);
  }
}
