/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DbcCategoryService } from "../dbcCategory.service";
import { DbcCategoryCreateInput } from "./DbcCategoryCreateInput";
import { DbcCategory } from "./DbcCategory";
import { DbcCategoryFindManyArgs } from "./DbcCategoryFindManyArgs";
import { DbcCategoryWhereUniqueInput } from "./DbcCategoryWhereUniqueInput";
import { DbcCategoryUpdateInput } from "./DbcCategoryUpdateInput";
import { DbcParsedDataFindManyArgs } from "../../dbcParsedData/base/DbcParsedDataFindManyArgs";
import { DbcParsedData } from "../../dbcParsedData/base/DbcParsedData";
import { DbcParsedDataWhereUniqueInput } from "../../dbcParsedData/base/DbcParsedDataWhereUniqueInput";

export class DbcCategoryControllerBase {
  constructor(protected readonly service: DbcCategoryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DbcCategory })
  async createDbcCategory(
    @common.Body() data: DbcCategoryCreateInput
  ): Promise<DbcCategory> {
    return await this.service.createDbcCategory({
      data: data,
      select: {
        categoryName: true,
        createdAt: true,
        description: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [DbcCategory] })
  @ApiNestedQuery(DbcCategoryFindManyArgs)
  async dbcCategories(@common.Req() request: Request): Promise<DbcCategory[]> {
    const args = plainToClass(DbcCategoryFindManyArgs, request.query);
    return this.service.dbcCategories({
      ...args,
      select: {
        categoryName: true,
        createdAt: true,
        description: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DbcCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async dbcCategory(
    @common.Param() params: DbcCategoryWhereUniqueInput
  ): Promise<DbcCategory | null> {
    const result = await this.service.dbcCategory({
      where: params,
      select: {
        categoryName: true,
        createdAt: true,
        description: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DbcCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDbcCategory(
    @common.Param() params: DbcCategoryWhereUniqueInput,
    @common.Body() data: DbcCategoryUpdateInput
  ): Promise<DbcCategory | null> {
    try {
      return await this.service.updateDbcCategory({
        where: params,
        data: data,
        select: {
          categoryName: true,
          createdAt: true,
          description: true,
          id: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DbcCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDbcCategory(
    @common.Param() params: DbcCategoryWhereUniqueInput
  ): Promise<DbcCategory | null> {
    try {
      return await this.service.deleteDbcCategory({
        where: params,
        select: {
          categoryName: true,
          createdAt: true,
          description: true,
          id: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/dbcParsedDataItems")
  @ApiNestedQuery(DbcParsedDataFindManyArgs)
  async findDbcParsedDataItems(
    @common.Req() request: Request,
    @common.Param() params: DbcCategoryWhereUniqueInput
  ): Promise<DbcParsedData[]> {
    const query = plainToClass(DbcParsedDataFindManyArgs, request.query);
    const results = await this.service.findDbcParsedDataItems(params.id, {
      ...query,
      select: {
        codeName: true,
        codeValue: true,
        createdAt: true,
        dataType: true,

        dbcCategory: {
          select: {
            id: true,
          },
        },

        description: true,

        device: {
          select: {
            id: true,
          },
        },

        fileImportLog: {
          select: {
            id: true,
          },
        },

        id: true,
        rawData: true,
        sourceLine: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        valid: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/dbcParsedDataItems")
  async connectDbcParsedDataItems(
    @common.Param() params: DbcCategoryWhereUniqueInput,
    @common.Body() body: DbcParsedDataWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dbcParsedDataItems: {
        connect: body,
      },
    };
    await this.service.updateDbcCategory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/dbcParsedDataItems")
  async updateDbcParsedDataItems(
    @common.Param() params: DbcCategoryWhereUniqueInput,
    @common.Body() body: DbcParsedDataWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dbcParsedDataItems: {
        set: body,
      },
    };
    await this.service.updateDbcCategory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/dbcParsedDataItems")
  async disconnectDbcParsedDataItems(
    @common.Param() params: DbcCategoryWhereUniqueInput,
    @common.Body() body: DbcParsedDataWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dbcParsedDataItems: {
        disconnect: body,
      },
    };
    await this.service.updateDbcCategory({
      where: params,
      data,
      select: { id: true },
    });
  }
}
