/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DbcCategory } from "./DbcCategory";
import { DbcCategoryCountArgs } from "./DbcCategoryCountArgs";
import { DbcCategoryFindManyArgs } from "./DbcCategoryFindManyArgs";
import { DbcCategoryFindUniqueArgs } from "./DbcCategoryFindUniqueArgs";
import { CreateDbcCategoryArgs } from "./CreateDbcCategoryArgs";
import { UpdateDbcCategoryArgs } from "./UpdateDbcCategoryArgs";
import { DeleteDbcCategoryArgs } from "./DeleteDbcCategoryArgs";
import { DbcParsedDataFindManyArgs } from "../../dbcParsedData/base/DbcParsedDataFindManyArgs";
import { DbcParsedData } from "../../dbcParsedData/base/DbcParsedData";
import { DbcCategoryService } from "../dbcCategory.service";
@graphql.Resolver(() => DbcCategory)
export class DbcCategoryResolverBase {
  constructor(protected readonly service: DbcCategoryService) {}

  async _dbcCategoriesMeta(
    @graphql.Args() args: DbcCategoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [DbcCategory])
  async dbcCategories(
    @graphql.Args() args: DbcCategoryFindManyArgs
  ): Promise<DbcCategory[]> {
    return this.service.dbcCategories(args);
  }

  @graphql.Query(() => DbcCategory, { nullable: true })
  async dbcCategory(
    @graphql.Args() args: DbcCategoryFindUniqueArgs
  ): Promise<DbcCategory | null> {
    const result = await this.service.dbcCategory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DbcCategory)
  async createDbcCategory(
    @graphql.Args() args: CreateDbcCategoryArgs
  ): Promise<DbcCategory> {
    return await this.service.createDbcCategory({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => DbcCategory)
  async updateDbcCategory(
    @graphql.Args() args: UpdateDbcCategoryArgs
  ): Promise<DbcCategory | null> {
    try {
      return await this.service.updateDbcCategory({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DbcCategory)
  async deleteDbcCategory(
    @graphql.Args() args: DeleteDbcCategoryArgs
  ): Promise<DbcCategory | null> {
    try {
      return await this.service.deleteDbcCategory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [DbcParsedData], { name: "dbcParsedDataItems" })
  async findDbcParsedDataItems(
    @graphql.Parent() parent: DbcCategory,
    @graphql.Args() args: DbcParsedDataFindManyArgs
  ): Promise<DbcParsedData[]> {
    const results = await this.service.findDbcParsedDataItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
