/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  FileImportLog as PrismaFileImportLog,
  DbcParsedData as PrismaDbcParsedData,
} from "@prisma/client";

export class FileImportLogServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.FileImportLogCountArgs, "select">
  ): Promise<number> {
    return this.prisma.fileImportLog.count(args);
  }

  async fileImportLogs(
    args: Prisma.FileImportLogFindManyArgs
  ): Promise<PrismaFileImportLog[]> {
    return this.prisma.fileImportLog.findMany(args);
  }
  async fileImportLog(
    args: Prisma.FileImportLogFindUniqueArgs
  ): Promise<PrismaFileImportLog | null> {
    return this.prisma.fileImportLog.findUnique(args);
  }
  async createFileImportLog(
    args: Prisma.FileImportLogCreateArgs
  ): Promise<PrismaFileImportLog> {
    return this.prisma.fileImportLog.create(args);
  }
  async updateFileImportLog(
    args: Prisma.FileImportLogUpdateArgs
  ): Promise<PrismaFileImportLog> {
    return this.prisma.fileImportLog.update(args);
  }
  async deleteFileImportLog(
    args: Prisma.FileImportLogDeleteArgs
  ): Promise<PrismaFileImportLog> {
    return this.prisma.fileImportLog.delete(args);
  }

  async findDbcParsedDataItems(
    parentId: string,
    args: Prisma.DbcParsedDataFindManyArgs
  ): Promise<PrismaDbcParsedData[]> {
    return this.prisma.fileImportLog
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .dbcParsedDataItems(args);
  }
}
