/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FileImportLogService } from "../fileImportLog.service";
import { FileImportLogCreateInput } from "./FileImportLogCreateInput";
import { FileImportLog } from "./FileImportLog";
import { FileImportLogFindManyArgs } from "./FileImportLogFindManyArgs";
import { FileImportLogWhereUniqueInput } from "./FileImportLogWhereUniqueInput";
import { FileImportLogUpdateInput } from "./FileImportLogUpdateInput";
import { DbcParsedDataFindManyArgs } from "../../dbcParsedData/base/DbcParsedDataFindManyArgs";
import { DbcParsedData } from "../../dbcParsedData/base/DbcParsedData";
import { DbcParsedDataWhereUniqueInput } from "../../dbcParsedData/base/DbcParsedDataWhereUniqueInput";

export class FileImportLogControllerBase {
  constructor(protected readonly service: FileImportLogService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FileImportLog })
  async createFileImportLog(
    @common.Body() data: FileImportLogCreateInput
  ): Promise<FileImportLog> {
    return await this.service.createFileImportLog({
      data: data,
      select: {
        createdAt: true,
        fileName: true,
        id: true,
        importStatus: true,
        updatedAt: true,
        uploadDate: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [FileImportLog] })
  @ApiNestedQuery(FileImportLogFindManyArgs)
  async fileImportLogs(
    @common.Req() request: Request
  ): Promise<FileImportLog[]> {
    const args = plainToClass(FileImportLogFindManyArgs, request.query);
    return this.service.fileImportLogs({
      ...args,
      select: {
        createdAt: true,
        fileName: true,
        id: true,
        importStatus: true,
        updatedAt: true,
        uploadDate: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FileImportLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async fileImportLog(
    @common.Param() params: FileImportLogWhereUniqueInput
  ): Promise<FileImportLog | null> {
    const result = await this.service.fileImportLog({
      where: params,
      select: {
        createdAt: true,
        fileName: true,
        id: true,
        importStatus: true,
        updatedAt: true,
        uploadDate: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FileImportLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFileImportLog(
    @common.Param() params: FileImportLogWhereUniqueInput,
    @common.Body() data: FileImportLogUpdateInput
  ): Promise<FileImportLog | null> {
    try {
      return await this.service.updateFileImportLog({
        where: params,
        data: data,
        select: {
          createdAt: true,
          fileName: true,
          id: true,
          importStatus: true,
          updatedAt: true,
          uploadDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FileImportLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFileImportLog(
    @common.Param() params: FileImportLogWhereUniqueInput
  ): Promise<FileImportLog | null> {
    try {
      return await this.service.deleteFileImportLog({
        where: params,
        select: {
          createdAt: true,
          fileName: true,
          id: true,
          importStatus: true,
          updatedAt: true,
          uploadDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/dbcParsedDataItems")
  @ApiNestedQuery(DbcParsedDataFindManyArgs)
  async findDbcParsedDataItems(
    @common.Req() request: Request,
    @common.Param() params: FileImportLogWhereUniqueInput
  ): Promise<DbcParsedData[]> {
    const query = plainToClass(DbcParsedDataFindManyArgs, request.query);
    const results = await this.service.findDbcParsedDataItems(params.id, {
      ...query,
      select: {
        codeName: true,
        codeValue: true,
        createdAt: true,
        dataType: true,

        dbcCategory: {
          select: {
            id: true,
          },
        },

        description: true,

        device: {
          select: {
            id: true,
          },
        },

        fileImportLog: {
          select: {
            id: true,
          },
        },

        id: true,
        rawData: true,
        sourceLine: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        valid: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/dbcParsedDataItems")
  async connectDbcParsedDataItems(
    @common.Param() params: FileImportLogWhereUniqueInput,
    @common.Body() body: DbcParsedDataWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dbcParsedDataItems: {
        connect: body,
      },
    };
    await this.service.updateFileImportLog({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/dbcParsedDataItems")
  async updateDbcParsedDataItems(
    @common.Param() params: FileImportLogWhereUniqueInput,
    @common.Body() body: DbcParsedDataWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dbcParsedDataItems: {
        set: body,
      },
    };
    await this.service.updateFileImportLog({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/dbcParsedDataItems")
  async disconnectDbcParsedDataItems(
    @common.Param() params: FileImportLogWhereUniqueInput,
    @common.Body() body: DbcParsedDataWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dbcParsedDataItems: {
        disconnect: body,
      },
    };
    await this.service.updateFileImportLog({
      where: params,
      data,
      select: { id: true },
    });
  }
}
