/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { FileImportLog } from "./FileImportLog";
import { FileImportLogCountArgs } from "./FileImportLogCountArgs";
import { FileImportLogFindManyArgs } from "./FileImportLogFindManyArgs";
import { FileImportLogFindUniqueArgs } from "./FileImportLogFindUniqueArgs";
import { CreateFileImportLogArgs } from "./CreateFileImportLogArgs";
import { UpdateFileImportLogArgs } from "./UpdateFileImportLogArgs";
import { DeleteFileImportLogArgs } from "./DeleteFileImportLogArgs";
import { DbcParsedDataFindManyArgs } from "../../dbcParsedData/base/DbcParsedDataFindManyArgs";
import { DbcParsedData } from "../../dbcParsedData/base/DbcParsedData";
import { FileImportLogService } from "../fileImportLog.service";
@graphql.Resolver(() => FileImportLog)
export class FileImportLogResolverBase {
  constructor(protected readonly service: FileImportLogService) {}

  async _fileImportLogsMeta(
    @graphql.Args() args: FileImportLogCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [FileImportLog])
  async fileImportLogs(
    @graphql.Args() args: FileImportLogFindManyArgs
  ): Promise<FileImportLog[]> {
    return this.service.fileImportLogs(args);
  }

  @graphql.Query(() => FileImportLog, { nullable: true })
  async fileImportLog(
    @graphql.Args() args: FileImportLogFindUniqueArgs
  ): Promise<FileImportLog | null> {
    const result = await this.service.fileImportLog(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FileImportLog)
  async createFileImportLog(
    @graphql.Args() args: CreateFileImportLogArgs
  ): Promise<FileImportLog> {
    return await this.service.createFileImportLog({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => FileImportLog)
  async updateFileImportLog(
    @graphql.Args() args: UpdateFileImportLogArgs
  ): Promise<FileImportLog | null> {
    try {
      return await this.service.updateFileImportLog({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => FileImportLog)
  async deleteFileImportLog(
    @graphql.Args() args: DeleteFileImportLogArgs
  ): Promise<FileImportLog | null> {
    try {
      return await this.service.deleteFileImportLog(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [DbcParsedData], { name: "dbcParsedDataItems" })
  async findDbcParsedDataItems(
    @graphql.Parent() parent: FileImportLog,
    @graphql.Args() args: DbcParsedDataFindManyArgs
  ): Promise<DbcParsedData[]> {
    const results = await this.service.findDbcParsedDataItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
